### ISSUE TITLE
Better validation for flatten-maven-plugin

### ISSUE THREAD

**Issue by suztomo** [googleapis/java-shared-config#525]
https://github.com/googleapis/java-shared-config/pull/507 is failing with the downstream java-storage test.

This is the fix I recently made https://github.com/mojohaus/flatten-maven-plugin/issues/185 to the flatten-maven-plugin. The treatment of test-scope dependencies were incorrect.

We need to adjust the validation in dependencies.sh for the fixed behavior.

**Comment by meltsufin** [comment]
Why does the validation need to be adjusted if the fix is in?

**Comment by suztomo** [comment]
Because the validation was relying on the previous incorrect behavior of flatten-maven-plugin.

(What's the incorrect behavior? https://github.com/mojohaus/flatten-maven-plugin/issues/185 has diagram to explain the dependency in test-scope.)

**Comment by suztomo** [comment]
https://github.com/googleapis/synthtool/pull/1663/files is 1st step to remove the check in each repository.

**Comment by suztomo** [comment]
Reopening this until java-storage receives the OwlBot template change in https://github.com/googleapis/synthtool/pull/1663

**Comment by diegomarquezp** [comment]
Closing as `java-storage` got the template change merged in https://github.com/googleapis/java-storage/pull/1732
