### ISSUE TITLE
 Failed to determine Java version for profile checkstyle-tests

### ISSUE THREAD

**Issue by elharo** [googleapis/java-shared-config#61]
Seeing this in libraries-bom:

 Failed to determine Java version for profile checkstyle-tests @ com.google.cloud:google-cloud-shared-config:0.2.1, /home/elharo/.m2/repository/com/google/cloud/google-cloud-shared-config/0.2.1/google-cloud-shared-config-0.2.1.pom, line 406, column 14

**Comment by elharo** [comment]
Perhaps relevant: http://maven.40175.n5.nabble.com/Failed-to-determine-Java-version-for-profile-jdk-td5073097.html

**Comment by elharo** [comment]
Problem might be that the profiles add dependencies on different versions of autovalue depending on JDK version. 

Autovalue should not be a dependency. Instead it should be on the annottionprocessorpath.

**Comment by elharo** [comment]
also similar: https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/issues/45

**Comment by elharo** [comment]
This seems to have started with the first release to use the shared config, 0.117.0

**Comment by suztomo** [comment]
I was able to reproduce the error. Checking further.

```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ integration-tests ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.cloud.MaximumLinkageErrorsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.673 s <<< FAILURE! - in com.google.cloud.MaximumLinkageErrorsTest
[ERROR] testMaximumLinkageErrors(com.google.cloud.MaximumLinkageErrorsTest)  Time elapsed: 0.645 s  <<< ERROR!
com.google.cloud.tools.opensource.dependencies.MavenRepositoryException: 
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Failed to determine Java version for profile checkstyle-tests @ com.google.cloud:google-cloud-shared-config:0.2.1, /usr/local/google/home/suztomo/.m2/repository/com/google/cloud/google-cloud-shared-config/0.2.1/google-cloud-shared-config-0.2.1.pom, line 406, column 14

```
