### ISSUE TITLE
A check to detect javadoc plugin malfunction

### ISSUE THREAD

**Issue by suztomo** [googleapis/java-shared-config#661]
Let's implement a check to detect javadoc plugin malfunction. We already have test, lint, and clirr jobs in https://github.com/googleapis/java-shared-config/blob/main/.github/workflows/downstream-maven-plugins.yaml.

@alicejli observed the following error:

```
Execution default-cli of goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.0:aggregate failed: If a non-null excludes list is given, all elements must be non-null -> [Help 1]
```

**Comment by alicejli** [comment]
Fixed with https://github.com/googleapis/java-shared-config/pull/662
