### ISSUE TITLE
Debug why javadoc generation fails with maven-javadoc-plugin v3.6.0

### ISSUE THREAD

**Issue by alicejli** [googleapis/java-shared-config#680]
Breaking this off from https://github.com/googleapis/java-shared-config/issues/673 as that will be the tracking bug for migrating handwritten libraries to use the version of maven-javadoc-plugin from java-shared-config, and this will be the new tracking bug for debugging why javadoc generation fails with the doclet used for Cloud RAD when the maven-javadoc-plugin is upgraded to v3.6.0.

**Comment by suztomo** [comment]
Memo: javadoc-with-doclet check has been installed since then https://github.com/googleapis/java-shared-config/blob/28b2c77ddd2078d628cb8f2b16fae8efd0e673a5/.github/workflows/downstream-maven-plugins.yaml#L36 to prevent accidentally bumping maven-javadoc-plugin version.
