### ISSUE TITLE
Automate update to java-shared-config docker image tag

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/java-shared-config#691]
Currently, the docker image tag needs to be updated manually. See https://github.com/googleapis/java-shared-config/pull/690. 
- Verify if `<!-- {x-version-update:google-cloud-shared-config:current} -->` works on yaml files.

**Comment by suztomo** [comment]
`<!--` is not YAML comment.

"extraFiles" in Release Please may help. https://github.com/googleapis/java-storage/blob/main/.github/release-please.yml#L4 and https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files

**Comment by mpeddada1** [comment]
Release Please is now set up to automatically update image tags (https://github.com/googleapis/java-shared-config/pull/733) after changes in #720 and #729
