### ISSUE TITLE
Verify update of cloudbuild-test-*.yaml files in upcoming release

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/java-shared-config#730]
Part of https://github.com/googleapis/java-shared-config/issues/691

The release-please.yml file was updated to include these files (https://github.com/googleapis/java-shared-config/pull/728) while this [release PR was already open ](https://github.com/googleapis/java-shared-config/pull/727). However, add the `release-please:force-run` label to PR 728 and 727 (as documented in https://github.com/googleapis/release-please/blob/main/README.md#step-3-rerun-release-please) and closing and re-opening the release PR didn't do the trick. 

On the other hand, adding the  `cloudbuild.yaml` file to the `extra-files` field in release-please.yaml with an inline annotation `x-version-update:<artifact-name>:released` worked. 

Reference for both settings:
- https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files
- https://github.com/googleapis/release-please/blob/main/docs/java-releases.md

**Comment by suztomo** [comment]
The document you referenced has "Updating arbitrary YAML files" section. 

![image](https://github.com/googleapis/java-shared-config/assets/28604/ab5a1745-f42c-4ebd-a91e-740d6dc38b06)

I don't see https://github.com/googleapis/java-shared-config/pull/728 followed this.

**Comment by mpeddada1** [comment]
[Update] It looks like the update to `release-please.yml` is working now? https://github.com/googleapis/java-shared-config/pull/731

**Comment by suztomo** [comment]
Nice. Then check with next Release Please pull request for non-snapshot version.

**Comment by mpeddada1** [comment]
Verified that it is being updated for non-snapshot versions as well: https://github.com/googleapis/java-shared-config/pull/733. Closing issue.
