### ISSUE TITLE
client-library-check.sh fails

### ISSUE THREAD

**Issue by alicejli** [googleapis/java-shared-config#745]
The consolidation of build configs: https://github.com/googleapis/java-spanner/pull/2865 is causing the downstream `client-library-check.sh` to fail (currently failing for java-spanner and java-pubsub as those repos have had the change implemented).

This is because the downstream check replaces the `google-cloud-shared-config` artifact in the pom.xml and checks that it compiles. However, the consolidation of the build configs removes the `google-cloud-shared-config` artifact from the pom.xml so the test has nothing to replace. The tests will need to be reworked to account for this build config change.

**Comment by mpeddada1** [comment]
Fixed with https://github.com/googleapis/java-shared-config/pull/746
